language: php

sudo: false

php:
  - 5.6

matrix:
  fast_finish: true

env:
  matrix:
  - SCENARIO=none DF=HEAD
  - SCENARIO=none DF=STABLE
  - SCENARIO=dfs_dev DF=STABLE
  - SCENARIO=dfs_tec DF=STABLE

# Cache Composer & Drush directories.
cache:
  bundler: true
  apt: true
  directories:
    - "$HOME/.composer/cache"
    - "$HOME/.drush/cache"

mysql:
  database: drupal
  username: root
  encoding: utf8

before_install:
  # Disable xdebug.
  - phpenv config-rm xdebug.ini
  # Update composer.
  - composer self-update
  - composer --version
  # Add the oauth token to prevent GitHub timeouts.
  - git config --global github.accesstoken $GITHUB_OAUTH_TOKEN

install:
  # Add Composer's local bin directory to the PATH so that we will be running
  # our installed versions of Drush, PHPCS, Behat, PhantomJS, etc.
  - export PATH="$TRAVIS_BUILD_DIR/bin:$PATH"

  # Composer install should fail on bad patches.
  - export COMPOSER_EXIT_ON_PATCH_FAILURE=1

  # MySQL Options
  - mysql -e 'SET GLOBAL wait_timeout = 5400;'
  - mysql -e "SHOW VARIABLES LIKE 'wait_timeout'"

  # PHP conf tweaks
  - echo 'max_execution_time = 120' >> drupal.php.ini;
  - echo 'sendmail_path = /bin/true' >> drupal.php.ini;
  - phpenv config-add drupal.php.ini
  - phpenv rehash

  # Test DF HEAD
  - if [[ "$DF" == HEAD ]]; then composer require "drupal/df:dev-8.x-1.x" --no-update; fi

  # Let Composer do all the magic!
  - composer install

  # Install DF.
  - cd docroot
  - drush site-install df --yes --account-pass=admin --db-url=mysql://root:@localhost/drupal
  - drush config-set system.performance css.preprocess 0 --yes --format=boolean
  - drush config-set system.performance js.preprocess 0 --yes --format=boolean
  - drush config-set system.logging error_level all --yes

  # If a scenario has been specified, enable it.
  - if [[ "$SCENARIO" != none ]]; then drush es $SCENARIO; fi
  - cd ..

before_script:
  - cd docroot
  - drush runserver --default-server=builtin 8080 &>/dev/null &
  - phantomjs --webdriver=4444 > /dev/null &
  - cd ..

script:
  - cd docroot/profiles/df
  - phpcs --standard=$TRAVIS_BUILD_DIR/vendor/drupal/coder/coder_sniffer/Drupal/ruleset.xml --ignore=bin,*.css,libraries,modules/contrib . || true
  - if [[ "$SCENARIO" == none ]]; then behat --strict --tags=df; fi
  - if [[ "$SCENARIO" != none ]]; then behat --strict --tags=$SCENARIO; fi

after_failure:
  - $TRAVIS_BUILD_DIR/vendor/lakion/mink-debug-extension/travis/tools/upload-textfiles "tests/build/*.log"
  - $TRAVIS_BUILD_DIR/vendor/lakion/mink-debug-extension/travis/tools/upload-screenshots "tests/build/*.png"
